% Feature extraction for both datasets 

[features_kismet, labels_kismet,aFE] = extract_features(kismet,kismet_fs);
[features_babyYears, labels_babyYears] = extract_features(babyYears,babyYears_fs);

save('.\features\features_kismet.mat','features_kismet','kismet_fs','labels_kismet')
save('.\features\features_babyYears.mat','features_babyYears','babyYears_fs','labels_babyYears')
save('.\features\aFE.mat','features_babyYears','aFE')

function [features,labels,afe] = extract_features(data,fs)

    win = hamming(round(0.03*fs),"periodic");
    overlapLength = round(0.02*fs);
    
    afe = audioFeatureExtractor( ...
        'Window',              win, ...
        'OverlapLength',       overlapLength, ...
        'SampleRate',          fs, ...
        ...
        'linearSpectrum',      false, ...
        'melSpectrum',         true, ...
        'barkSpectrum',        false, ...
        'erbSpectrum',         false, ...
        ...
        'mfcc',                true, ...
        'mfccDelta',           true, ...
        'mfccDeltaDelta',      true, ...
        'gtcc',                true, ...
        'gtccDelta',           true, ...
        'gtccDeltaDelta',      true, ...
        ...
        'spectralCentroid',    true, ...
        'spectralCrest',       true, ...
        'spectralDecrease',    true, ...
        'spectralEntropy',     true, ...
        'spectralFlatness',    true, ...
        'spectralFlux',        false, ...
        'spectralKurtosis',    true, ...
        'spectralRolloffPoint',true, ...
        'spectralSkewness',    true, ...
        'spectralSlope',       false, ...
        'spectralSpread',      true, ...
        ...
        'pitch',               false, ...
        'harmonicRatio',       false);

    features = {};
    labels = {};

    for i = 1:length(data)
        signal = data(i).Data.amplitude;
        
        feat = extract(afe,signal)';

        if ~isempty(feat)
            lab = data(i).Label;
            if strcmp(lab,'pr')
                lab = 'pw';
            end
            labels = [labels lab];
            features = [features feat];
        end
    end

end
